# Generated by Django 4.2.2 on 2023-06-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('width', models.FloatField(verbose_name=0)),
                ('height', models.FloatField(verbose_name=0)),
                ('depth', models.FloatField(verbose_name=0)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.artists')),
            ],
        ),
    ]
