# Generated by Django 4.2.2 on 2023-06-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='birth_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artists',
            name='death_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.artists'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='depth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
