# Generated by Django 4.2.2 on 2023-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_alter_artists_birth_date_alter_artists_death_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='death_date',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
