# Generated by Django 4.2.2 on 2023-06-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_alter_artists_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='birth_date',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
