# Generated by Django 4.2.2 on 2023-06-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_alter_artists_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
    ]
